version: 2
updates:
- package-ecosystem: docker
  directory: metricshub-jre-docker
  schedule:
    interval: weekly
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly