name: Build JRE

on:
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

env:
  JDK_VERSION: 17.0.12+7

jobs:
  build-jre:
    name: Build JRE

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: ${{ env.JDK_VERSION }}
        distribution: temurin

    - name: Build Linux JRE
      if: runner.os == 'Linux'
      run: |
        jlinkModules=$(cat modules.txt | tr '\n' ',')
        jlink --strip-debug --no-header-files --no-man-pages --add-modules $jlinkModules --output jre-linux
        echo "JRE_OS_NAME=linux">>${GITHUB_ENV}

    - name: Build Windows JRE
      if: runner.os == 'Windows'
      run: |
        $jlinkModules = (Get-Content modules.txt) -join ','
        jlink --strip-debug --no-header-files --no-man-pages --add-modules $jlinkModules --output jre-windows
        echo "JRE_OS_NAME=windows" >> $env:GITHUB_ENV

    - name: Upload JRE
      uses: actions/upload-artifact@v4
      with:
        name: metricshub-jre-${{ env.JDK_VERSION }}-${{ env.JRE_OS_NAME }}
        path: jre-${{ env.JRE_OS_NAME }}/

  build-jre-docker:
    name: Build JRE Docker Image

    runs-on: ubuntu-latest

    steps:
    -
      # Add support for more platforms with QEMU (optional)
      # https://github.com/docker/setup-qemu-action
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3
      with:
        platforms: linux/amd64,linux/arm64
        buildkitd-config: |
          {
            "debug": true,
            "features": {
              "containerd-snapshotter": true
            }
          }

    - 
      # Docker Images Does Not Contains the plus (+) sign
      # Must be replaced with underscore (_)
      name: Prepare version number
      run: echo "JDK_IMAGE_TAG=${{ env.JDK_VERSION }}" | sed 's/+/_/g' >> $GITHUB_ENV

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        build-args: |
          JDK_VERSION=${{ env.JDK_IMAGE_TAG }}
        platforms: linux/amd64,linux/arm64
        load: true
        tags: user/app:latest
