name: Build JRE

on:
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

env:
  JDK_VERSION: 17.0.12+7

jobs:
  build-jre:
    name: Build JRE

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: ${{ env.JDK_VERSION }}
        distribution: temurin

    - name: Build Linux JRE
      if: runner.os == 'Linux'
      run: |
        jlinkModules=$(cat modules.txt | tr '\n' ',')
        jlink --strip-debug --no-header-files --no-man-pages --add-modules $jlinkModules --output jre-linux
        echo "JRE_OS_NAME=linux">>${GITHUB_ENV}

    - name: Build Windows JRE
      if: runner.os == 'Windows'
      run: |
        $jlinkModules = (Get-Content modules.txt) -join ','
        jlink --strip-debug --no-header-files --no-man-pages --add-modules $jlinkModules --output jre-windows
        echo "JRE_OS_NAME=windows">>${GITHUB_ENV}

    - name: Upload JRE
      uses: actions/upload-artifact@v4
      with:
        name: jre-${{ env.JDK_VERSION }}-${{ env.JRE_OS_NAME }}
        path: jre-${{ env.JRE_OS_NAME }}/
