name: Deploy JRE

on:
  workflow_dispatch:
    inputs:
      REPOSITORY:
        description: 'Repository name'
        required: true
        default: ${{ github.repository }}
      BUILD_RUN_ID:
        description: 'Build run id'
        required: true

jobs:
  deploy-jre:
    name: Deploy JRE

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Get Build Artifact
      uses: actions/download-artifact@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        repository: ${{ github.repository }}
        run_id: ${{ github.run_id }}

    - name: Linux
      if: runner.os == 'Linux'
      run: |
        ls -al

    - name: Windows
      if: runner.os == 'Windows'
      run: |
        Get-ChildItem

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: ${{ env.JDK_VERSION }}
        distribution: temurin
        java-package: jdk
        cache: maven

    - name: Maven Deploy Archives
      if: ${{ env.DEPLOY_ARCHIVES == 'true' }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
        GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
        GITHUB_REPOSITORY: ${{ github.repository }}
      run: |
        mvn deploy:deploy-file -Durl=https://maven.pkg.github.com/${{ env.GITHUB_REPOSITORY_OWNER }}/${{ env.GITHUB_REPOSITORY }} -Dfile=metricshub-jre-${{ env.JRE_OS_NAME }}.zip -DgroupId=org.sentrysoftware -DartifactId=metricshub-jre-${{ env.JRE_OS_NAME }} -Dversion=${{ env.JDK_VERSION }} -Dpackaging=jlink "-Ddescription=MetricsHub JRE for ${{ runner.os }}"

#  deploy-jre-docker:
#    name: Deploy JRE (docker)
#
#    runs-on: ubuntu-latest
#
#    steps:
#    -
#      name: Login to Docker Hub
#      uses: docker/login-action@v3
#      with:
#        username: ${{ vars.DOCKERHUB_USERNAME }}
#        password: ${{ secrets.DOCKERHUB_TOKEN }}
#
#    -
#      # Add support for more platforms with QEMU (optional)
#      # https://github.com/docker/setup-qemu-action
#      name: Set up QEMU
#      uses: docker/setup-qemu-action@v3
#
#    - name: Set up Docker
#      uses: docker/setup-buildx-action@v3
#
#    - 
#      # Docker Images Does Not Contains the plus (+) sign
#      # Must be replaced with underscore (_)
#      name: Prepare version number
#      run: echo "JDK_IMAGE_TAG=${{ env.JDK_VERSION }}" | sed 's/+/_/g' >> $GITHUB_ENV
#
#    - name: Build and push
#      uses: docker/build-push-action@v6
#      with:
#        build-args: |
#          JDK_VERSION=${{ env.JDK_IMAGE_TAG }}
#        platforms: linux/amd64,linux/arm64
#        push: ${{ env.DEPLOY_ARCHIVES }}
#        tags: ${{ vars.DOCKERHUB_ORG }}/metricshub-jre:latest,${{ vars.DOCKERHUB_ORG }}/metricshub-jre:${{ env.JDK_IMAGE_TAG }}
